---
layout: default
---

Empty `catch` and `finally` Block
=================================
A `try` without `catch` or `finally` is equivalent to putting
its body in a block; no exceptions are handled.

A `try` expression should be followed by some mechanism to handle any exceptions
thrown. Typically a `catch` expression follows the `try` and pattern matches
on any expected exceptions. For example:

```scala
import scala.util.control.NonFatal

try {
  ...
} catch {
  case NonFatal(e) => ???
}
```

It is recommended to use the `NonFatal` extractor to catch all exceptions as it
correctly handles transfer functions like `return`.

It is also possible to follow a `try` immediately by a `finally` - letting the
exception propagate - but still allowing for some clean up in `finally`:

```scala
try {
  ...
} finally {
  // perform your cleanup here!
}
```

A finally block will **always** run after the try expression - with our without
exceptions being thrown.
